import type { Metadata } from "next";
// import localFont from "next/font/local";
// import { Roboto } from "next/font/google";
import { Ubuntu } from "next/font/google";
import "./globals.css";

// const bitsumishi = localFont({
//    src: [
//       {
//          path: "./fonts/bitsumishi.ttf",
//          weight: "400",
//          style: "normal",
//       },
//    ],
//    variable: "--font-bitsumishi",
// });

// const roboto = Roboto({
//    weight: "400",
//    display: "swap",
//    variable: "--font-roboto",
// });
const ubuntu = Ubuntu({
   weight: "400",
   display: "swap",
   variable: "--font-ubuntu",
});

export const metadata: Metadata = {
   title: "Music App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={ubuntu.variable}>{children}</body>
      </html>
   );
}
